version: '3.9'
services:
  # api
  lms-api:
    container_name: lms-api
    image: lms-api:latest
    ports:
      - 3030:3030
    depends_on:
      - lms-postgres
    command: sh -c "dockerize -wait tcp://lms-postgres:5432 -timeout 300s -wait-retry-interval 30s ENV=DEV /go/bin/api"
    networks:
      - lms-net

  # elasticsearch
  lms-elasticsearch:
    container_name: lms-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    restart: always
    mem_limit: 512m
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - lms-net
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  # postgress
  lms-postgres:
    container_name: lms-postgres
    image: postgres:12-alpine
    restart: always
    depends_on:
      - lms-elasticsearch
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=postgres
      - APP_DB_PASS=password
      - APP_DB_NAME=db_lms
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - lms-postgres:/var/lib/postgresql
    ports:
      - '5432:5432'
    networks:
      - lms-net

volumes:
  lms-postgres:
  elasticsearch:

networks:
  lms-net:
    name: lms-net
    driver: bridge
